services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: sms
      POSTGRES_PASSWORD: sms
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
