CREATE TABLE teacher (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    date_of_birth DATE         NOT NULL,
    position      VARCHAR(20)  NOT NULL CHECK (position IN ('ASSISTANT', 'LECTURER', 'PROFESSOR'))
);

CREATE TABLE student (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    email           VARCHAR(255) NOT NULL UNIQUE,
    enrollment_year INT          NOT NULL CHECK (enrollment_year BETWEEN 2000 AND 2100),
    status          VARCHAR(20)  NOT NULL CHECK (status IN ('ACTIVE', 'ON_LEAVE', 'EXPELLED', 'GRADUATED'))
);

CREATE TABLE course (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)  NOT NULL,
    credits     INT           NOT NULL CHECK (credits BETWEEN 1 AND 60),
    description VARCHAR(2000),
    teacher_id  BIGINT REFERENCES teacher (id) ON DELETE RESTRICT
);

CREATE TABLE enrollment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT      NOT NULL REFERENCES student (id) ON DELETE CASCADE,
    course_id  BIGINT      NOT NULL REFERENCES course (id) ON DELETE RESTRICT,
    semester   SMALLINT    NOT NULL CHECK (semester IN (1, 2)),
    study_year INT         NOT NULL CHECK (study_year BETWEEN 2000 AND 2100),
    grade      VARCHAR(2)  NOT NULL DEFAULT 'NA' CHECK (grade IN ('A', 'B', 'C', 'D', 'F', 'NA')),
    paid       BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_enrollment UNIQUE (student_id, course_id, semester, study_year)
);
